### ISSUE TITLE
Example doesn't compile on OS X 10.11

### ISSUE THREAD

**Issue by wtholliday** [TheAmazingAudioEngine/TheAmazingAudioEngine#193]
```
AEReverbFilter.m:17:32: Use of undeclared identifier 'kAudioUnitSubType_Reverb2'; did you mean 'kAudioUnitSubType_Merger'?

AEReverbFilter.m:24:41: Use of undeclared identifier 'kReverb2Param_DryWetMix'; did you mean 'kReverbParam_DryWetMix'?

AEReverbFilter.m:28:41: Use of undeclared identifier 'kReverb2Param_Gain'; did you mean 'kPannerParam_Gain'?

AEReverbFilter.m:32:41: Use of undeclared identifier 'kReverb2Param_MinDelayTime'; did you mean 'kReverbParam_PreDelay'?

AEReverbFilter.m:36:41: Use of undeclared identifier 'kReverb2Param_MaxDelayTime'; did you mean 'kReverbParam_PreDelay'?

AEReverbFilter.m:40:41: Use of undeclared identifier 'kReverb2Param_DecayTimeAt0Hz'

AEReverbFilter.m:44:41: Use of undeclared identifier 'kReverb2Param_DecayTimeAtNyquist'

AEReverbFilter.m:48:41: Use of undeclared identifier 'kReverb2Param_RandomizeReflections'

AEReverbFilter.m:68:30: Use of undeclared identifier 'kReverb2Param_DryWetMix'; did you mean 'kReverbParam_DryWetMix'?

AEReverbFilter.m:73:30: Use of undeclared identifier 'kReverb2Param_Gain'; did you mean 'kPannerParam_Gain'?

AEReverbFilter.m:78:30: Use of undeclared identifier 'kReverb2Param_MinDelayTime'; did you mean 'kReverbParam_PreDelay'?

AEReverbFilter.m:83:30: Use of undeclared identifier 'kReverb2Param_MaxDelayTime'; did you mean 'kReverbParam_PreDelay'?

AEReverbFilter.m:88:30: Use of undeclared identifier 'kReverb2Param_DecayTimeAt0Hz'

AEReverbFilter.m:93:30: Use of undeclared identifier 'kReverb2Param_DecayTimeAtNyquist'

AEReverbFilter.m:98:30: Use of undeclared identifier 'kReverb2Param_RandomizeReflections'
```

**Comment by michaeltyson** [comment]
Right you are - this appears not to exist on the Mac. Fixed in a recent commit.
